SELECT * FROM DEPT;

INSERT INTO DEPT (DEPTNO,DNAME,LOC) VALUES (50, 'FINANCES', 'WASHINGTON DC');

UPDATE DEPT d SET d.LOC = (SELECT c.LOC FROM DEPT c WHERE c.DNAME = 'OPERATIONS') WHERE d.DNAME = 'FINANCES';


SELECT @loc1 := LOC FROM DEPT WHERE DNAME = 'OPERATIONS';
UPDATE DEPT d SET d.LOC = @loc1 WHERE d.DNAME = 'FINANCES';


-- MERGE INTO EMP
-- USING DEPT ON
-- WHEN MATCHED THEN
-- WHEN NOT MATCHED THEN
START TRANSACTION;
SELECT * FROM DEPT;
UPDATE DEPT SET LOC = 'HEVERLEE' WHERE DNAME = 'FINANCES';
ROLLBACK;
SELECT * FROM DEPT;

;

CREATE TABLE LEDEN (
lidnr	 		DECIMAL(5,0) not null PRIMARY KEY ,
lidnaam  		VARCHAR(50) NOT NULL,
lidwoonplaats	varchar(25)
);

DROP TABLE NIEUWE_LEDEN;

CREATE TABLE NIEUWE_LEDEN (
lidnr	 		INT  AUTO_INCREMENT PRIMARY KEY ,
lidnaam  		VARCHAR(50) NOT NULL,
lidwoonplaats	varchar(25)
);

CREATE TABLE ACTIVITEITEN (
ACTNR DECIMAL(3,0) NOT NULL PRIMARY KEY,
ACTNAAM VARCHAR(100) NOT NULL
);

CREATE TABLE DEELNAME (
LIDNR DECIMAL(5,0) NOT NULL ,
ACTNR DECIMAL(3,0) NOT NULL ,
DATUM DATETIME NOT NULL DEFAULT now(),
CONSTRAINT PK_DEELNAME PRIMARY KEY (LIDNR,ACTNR),
CONSTRAINT FK_LIDNR FOREIGN KEY (LIDNR) REFERENCES LEDEN(LIDNR),
CONSTRAINT FK_ACTNR FOREIGN KEY (ACTNR) REFERENCES ACTIVITEITEN(ACTNR)
);

INSERT INTO LEDEN (LIDNR,LIDNAAM,LIDWOONPLAATS) VALUES (0,'David M','Linter');
INSERT INTO LEDEN (LIDNR,LIDNAAM,LIDWOONPLAATS) VALUES (0,'David M','Linter');
INSERT INTO LEDEN (LIDNR,LIDNAAM,LIDWOONPLAATS) VALUES (1,'Geert','Hogevenne');
INSERT INTO LEDEN (LIDNR,LIDNAAM,LIDWOONPLAATS) VALUES (2,'Nancy','Mechelen');


INSERT INTO ACTIVITEITEN(ACTNR,ACTNAAM) VALUES (0,'JAVA');
INSERT INTO ACTIVITEITEN(ACTNR,ACTNAAM) VALUES (1,'SQL');

INSERT INTO DEELNAME(LIDNR,ACTNR,DATUM) VALUES (0,0,DEFAULT);
INSERT INTO DEELNAME(LIDNR,ACTNR,DATUM) VALUES (0,1,DEFAULT);
INSERT INTO DEELNAME(LIDNR,ACTNR,DATUM) VALUES (1,0,DEFAULT);
INSERT INTO DEELNAME(LIDNR,ACTNR,DATUM) VALUES (1,1,DEFAULT);
INSERT INTO DEELNAME(LIDNR,ACTNR,DATUM) VALUES (2,0,DEFAULT);
INSERT INTO DEELNAME(LIDNR,ACTNR,DATUM) VALUES (2,1,DEFAULT);
INSERT INTO DEELNAME(LIDNR,ACTNR,DATUM) VALUES (3,0,DEFAULT);

SELECT * FROM DEELNAME;

INSERT INTO NIEUWE_LEDEN (LIDNAAM,LIDWOONPLAATS) VALUES ('David M','Linter');
INSERT INTO NIEUWE_LEDEN (LIDNAAM,LIDWOONPLAATS) VALUES ('Geert','Hogevenne');
INSERT INTO NIEUWE_LEDEN (LIDNAAM,LIDWOONPLAATS) VALUES ('Nancy','Mechelen');
INSERT INTO NIEUWE_LEDEN (LIDNAAM,LIDWOONPLAATS) VALUES ('David Y','Mechelen');

SELECT * FROM NIEUWE_LEDEN;

UPDATE NIEUWE_LEDEN SET LIDNR = 4 WHERE LIDNR = 1;

CREATE VIEW VW_EMP_DEPT
AS
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE DEPTNO = 10;

CREATE UNIQUE INDEX ix_dname on dept(dname);

CREATE user david;

grant all on table emp to david;